### ISSUE TITLE
Python 35 - iteritems

### ISSUE THREAD

**Issue by djohnsonbaugh** [cvxgrp/dem#3]
It looks like issues related to converting to Python 3.x are not all resolved. 

Traceback (most recent call last):
  File "C:\repo\DWPSA\DWPSA\DWPSA.py", line 20, in <module>
    file.write(gp.results.summary())
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\dem\network.py", line 204, in summary
    for device_terminal, value in self.power.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by mwytock** [comment]
thanks for the report - will fix and add the appropriate tests to make sure everything is python3 compliant
