### ISSUE TITLE
MemoryError - low priority

### ISSUE THREAD

**Issue by djohnsonbaugh** [cvxgrp/dem#5]
CVXPY seemed to have run out of memory when I attempted the whole model (reduced)

Stations (Group & Net) - 29,549
Lines - 42,283
Units - 6,541
Fixed Load - 37,546

This may not be easily remedied, but good to know we have this limitation now. 

Traceback (most recent call last):
  File "main.py", line 698317, in <module>
    network.problem.solve()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\dem\network.py", line 163, in problem
    return sum(x.problem for x in self.devices + self.nets)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 569, in __add__
    list(set(self.constraints + other.constraints)))
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 78, in __init__
    self._size_metrics = SizeMetrics(self)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 671, in __init__
    for const in problem.constants()+problem.parameters():
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 159, in constants
    const_dict = {id(constant): constant for constant in constants_}
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 159, in <dictcomp>
    const_dict = {id(constant): constant for constant in constants_}
MemoryError

**Comment by mwytock** [comment]
Interesting, indeed a large problem.

If you could share a script for this problem or a similarly large random
problem that hits the same limit that would be helpful...

On Mar 8, 2017 5:40 PM, "DeWayne Johnsonbaugh" <notifications@github.com>
wrote:

CVXPY seemed to have run out of memory when I attempted the whole model
(reduced)

Stations (Group & Net) - 29,549
Lines - 42,283
Units - 6,541
Fixed Load - 37,546

This may not be easily remedied, but good to know we have this limitation
now.

Traceback (most recent call last):
File "main.py", line 698317, in
network.problem.solve()
File "C:\Program Files (x86)\Python35-32\lib\site-packages\dem\network.py",
line 163, in problem
return sum(x.problem for x in self.devices + self.nets)
File "C:\Program Files
(x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py",
line 569, in *add*
list(set(self.constraints + other.constraints)))
File "C:\Program Files
(x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py",
line 78, in *init*
self.



*size_metrics = SizeMetrics(self) File "C:\Program Files
(x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 671,
in init for const in problem.constants()+problem.parameters(): File
"C:\Program Files
(x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py", line 159,
in constants const_dict = {id(constant): constant for constant in constants*
}
File "C:\Program Files
(x86)\Python35-32\lib\site-packages\cvxpy\problems\problem.py",
line 159, in
const_dict = {id(constant): constant for constant in constants_}
MemoryError

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cvxgrp/dem/issues/5>, or mute the thread

**Comment by djohnsonbaugh** [comment]
I will make available an encrypted file shortly, rather not post that publicly.

**Comment by djohnsonbaugh** [comment]
Should i reinstall a 64bit version of Python and all libraries? Would that help?

**Comment by mwytock** [comment]
You could try, more memory is always good.

It looks like its hitting a limit on the python side rather than in the
underlying C libraries for the solver but I'd have to take a closer look to
see whats actually going on before being able to say if that would actually
help.
